version: 2

sources:
  - name: gfw
    description: Global Fishing Watch vessel presence data
    meta:
      external_location: "../data/gfw/*.json"
    tables:
      - name: vessel_presence_2024_01
        description: Vessel presence data for January 2024
        meta:
          external_location: "../data/gfw/2024-01.json"

      - name: vessel_presence_2024_02
        description: Vessel presence data for February 2024
        meta:
          external_location: "../data/gfw/2024-02.json"

      - name: vessel_presence_2024_03
        description: Vessel presence data for March 2024
        meta:
          external_location: "../data/gfw/2024-03.json"

      - name: vessel_presence_2024_04
        description: Vessel presence data for April 2024
        meta:
          external_location: "../data/gfw/2024-04.json"

      - name: vessel_presence_2024_05
        description: Vessel presence data for May 2024
        meta:
          external_location: "../data/gfw/2024-05.json"

      - name: vessel_presence_2024_06
        description: Vessel presence data for June 2024
        meta:
          external_location: "../data/gfw/2024-06.json"

      - name: vessel_presence_2024_07
        description: Vessel presence data for July 2024
        meta:
          external_location: "../data/gfw/2024-07.json"

      - name: vessel_presence_2024_08
        description: Vessel presence data for August 2024
        meta:
          external_location: "../data/gfw/2024-08.json"

      - name: vessel_presence_2024_09
        description: Vessel presence data for September 2024
        meta:
          external_location: "../data/gfw/2024-09.json"

      - name: vessel_presence_2024_10
        description: Vessel presence data for October 2024
        meta:
          external_location: "../data/gfw/2024-10.json"

      - name: vessel_presence_2024_11
        description: Vessel presence data for November 2024
        meta:
          external_location: "../data/gfw/2024-11.json"

      - name: vessel_presence_2024_12
        description: Vessel presence data for December 2024
        meta:
          external_location: "../data/gfw/2024-12.json"
