name: etl
version: '1.0.0'
profile: etl

model-paths: ["models"]
macro-paths: ["macros"]

models:
  etl:
    staging:
      +materialized: table
    intermediate:
      +materialized: table
    marts:
      +materialized: table
